// <auto-generated />
namespace BotHunter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Dialog_NameRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dialog_NameRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201801060719475_Dialog_NameRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
