// <auto-generated />
namespace BotHunter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_TopicTypeToEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_TopicTypeToEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201801041231056_Change_TopicTypeToEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
